project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('signup/', views.signup, name='signup'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email
    

class UserProfile(models.Model):
    user = models.OneToOneField('users.CustomUser', on_delete=models.CASCADE)
    age = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.user.email}'
    
    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'


@receiver(post_save, sender=CustomUser)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'email']

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.views.generic import TemplateView

from .forms import CustomUserCreationForm

def signup(request):
    form = CustomUserCreationForm()
    
    if request.method == 'POST': 
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower().strip()
            user.save()
            login(request, user)
            return redirect('users:home')

    return render(request, 'signup.html', {'form': form})


class HomeView(TemplateView):
    template_name = 'home.html'

users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-Profile</title>
</head>
<body>

    <nav>
        <h1><a href="{% url "users:home" %}">Home</a></h1>
    </nav>

    <div>
    {% block content %}
    {% endblock content %}
    </div>

</body>
</html>

users/templates/home.html
{% extends "base.html" %}

{% block content %}

<p><a href="{% url "users:signup" %}">Sign Up</a></p>

{% endblock content %}

users/templates/signup.html
{% extends "base.html" %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>

{% endblock content %}